---
- name: Install Harbor
  hosts: harbor_servers
  become: true
  vars:
    harbor_version: "2.8.0"
    harbor_install_dir: "/opt/harbor"
    harbor_config_file: "/opt/harbor/harbor.yml"
    harbor_download_url: "https://github.com/goharbor/harbor/releases/download/v{{ harbor_version }}/harbor-online-installer-v{{ harbor_version }}.tgz"

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: 
          - docker.io
          - docker-compose
          - curl
        state: present
        update_cache: yes

    - name: Download Harbor installer
      get_url:
        url: "{{ harbor_download_url }}"
        dest: "/tmp/harbor-online-installer-v{{ harbor_version }}.tgz"

    - name: Extract Harbor installer
      unarchive:
        src: "/tmp/harbor-online-installer-v{{ harbor_version }}.tgz"
        dest: "{{ harbor_install_dir }}"
        remote_src: yes

    - name: Copy Harbor configuration file
      template:
        src: "templates/harbor.yml.j2"
        dest: "{{ harbor_config_file }}"

    - name: Install Harbor
      command: "./install.sh"
      args:
        chdir: "{{ harbor_install_dir }}"

    - name: Start Harbor services
      command: "docker-compose up -d"
      args:
        chdir: "{{ harbor_install_dir }}"