- name: Prepare
  hosts: k8s_master,k8s_worker
  become: true
  tasks:
    # Install Docker packages
    - name: Install Docker packages
      apt:
        name: containerd.io
        state: present

    # Generate default containerd configuration
    - name: Generate default containerd configuration
      command: containerd config default
      register: containerd_config
      changed_when: false

    # Write containerd configuration to file
    - name: Write containerd configuration to file
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml

    # Update containerd configuration to use systemd cgroup
    - name: Update containerd configuration to use systemd cgroup
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*SystemdCgroup\s*=\s*false'
        line: 'SystemdCgroup = true'
        backrefs: yes

    # Restart and enable containerd
    - name: Restart and enable containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes