- name: Install NGINX Ingress Controller using Helm
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add the Helm stable repository
      ansible.builtin.command:
        cmd: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      register: helm_repo_add
      changed_when: "'\"has been added\"' in helm_repo_add.stdout"

    - name: Update Helm repositories
      ansible.builtin.command:
        cmd: helm repo update

    - name: Create a namespace for the ingress controller
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ingress-nginx

    - name: Install the NGINX Ingress Controller
      community.kubernetes.helm:
        name: nginx-ingress
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: false
        values:
          controller:
            replicaCount: 2
            service:
              type: LoadBalancer