- name: Install NGINX Ingress Controller using Helm
  hosts: k8s_master
  gather_facts: false
  tasks:
    - name: Ensure pip is installed
      ansible.builtin.raw: |
        apt-get update -y && apt-get install -y python3-pip
      changed_when: false

    - name: Ensure Python dependencies are installed
      ansible.builtin.raw: |
        python3 -m pip install --user openshift kubernetes
      changed_when: false

    - name: Pull the NGINX Ingress Controller chart
      ansible.builtin.command:
        cmd: helm pull oci://ghcr.io/nginx/charts/nginx-ingress --version 2.1.0 --untar
      args:
        chdir: /tmp

    - name: Create a namespace for the ingress controller
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: nginx-ingress

    - name: Install the NGINX Ingress Controller
      community.kubernetes.helm:
        name: nginx-ingress
        chart_ref: /tmp/nginx-ingress
        release_namespace: nginx-ingress
        create_namespace: false
        values:
          controller:
            replicaCount: 2
            service:
              type: NodePort
              nodePort: 30080