- name: Create an NGINX pod and service for testing
  hosts: k8s_master
  gather_facts: false
  tasks:
    - name: Create an NGINX pod
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: nginx-test
            namespace: default
          spec:
            containers:
              - name: nginx
                image: nginx:latest
                ports:
                  - containerPort: 80
        kubeconfig: /home/ubuntu/.kube/config
        remote_src: true

    - name: Expose the NGINX pod as a service
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: default
          spec:
            selector:
              app: nginx-test
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: NodePort
        kubeconfig: /home/ubuntu/.kube/config
        remote_src: true